version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'flaskmysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ntaticat'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Password123!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Password123!'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - mosquittoconf:/mosquitto/
    ports:
      - "1883:1883"
      - "9001:9001"
volumes:
  my-db:
  mosquittoconf: